mixed-port: 7890
allow-lan: false
mode: rule
log-level: warning
ipv6: true
external-controller: 127.0.0.1:9090
profile:
  store-fake-ip: true
dns:
  enable: true
  listen: ":53"
  ipv6: true
  default-nameserver:
    - tls://223.5.5.5
    - tcp://208.67.222.222:443
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  nameserver:
    - https://223.5.5.5/dns-query
    - https://1.0.0.1/dns-query
  fake-ip-filter:
    - +.stun.*.*
    - +.stun.*.*.*
    - +.stun.*.*.*.*
    - +.stun.*.*.*.*.*
    - "*.n.n.srv.nintendo.net"
    - +.stun.playstation.net
    - xbox.*.*.microsoft.com
    - "*.*.xboxlive.com"
    - "*.msftncsi.com"
    - "*.msftconnecttest.com"
    - WORKGROUP
#   fallback:
#     - tls://dns.rubyfish.cn:853
#     - tls://dns.google
#     - tls://1.1.1.1:853
#     - tcp://1.1.1.1:53
#     - https://1.1.1.1/dns-query
#   fallback-filter:
#     geoip: true
#     ipcidr:
#       - 240.0.0.0/4
